"""
scripts/build_assumptions_doc.py

Writes docs/assumptions.md: a plain-English table of every modelling choice
that does not come from a source (ASSUMPTIONS in src/compute/risk_calendar.py
and API_ASSUMPTIONS in app.py). The doc is generated, so edit the dicts and
re-run; src/api/test_assumptions_doc.py fails if the doc is out of date.

Run from the repo root:
    python scripts/build_assumptions_doc.py
"""

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT_MD = os.path.join(ROOT, "docs", "assumptions.md")


def cell(x):
    """One table cell: no pipes or line breaks."""
    return str(x).replace("|", "/").replace("\n", " ").strip()


def sensitivity_cell(entry):
    runs = entry.get("sensitivity")
    if runs:
        return "Yes: re-run with " + ", ".join(f"`{cell(r)}`" for r in runs)
    return "No"


def table(rows):
    out = ["| Name | Value | What it means | Why it is reasonable | Sensitivity run |",
           "|---|---|---|---|---|"]
    for name, e in rows.items():
        unit = f" {e['unit']}" if e.get("unit") else ""
        out.append(f"| `{name}` | {cell(e['value'])}{cell(unit)} | {cell(e['text'])} "
                   f"| {cell(e['why'])} | {sensitivity_cell(e)} |")
    return "\n".join(out)


def build():
    """The full text of docs/assumptions.md."""
    sys.path.insert(0, os.path.join(ROOT, "src", "compute"))
    sys.path.insert(0, ROOT)
    from risk_calendar import ASSUMPTIONS
    from app import API_ASSUMPTIONS
    return "\n".join([
        "# Survey Crops modelling choices",
        "",
        "<!-- Generated by scripts/build_assumptions_doc.py. Do not edit by hand. -->",
        "",
        "Where no source gave a number, the team chose one. They are listed here so "
        "they can be checked. Main choices are re-run with other values "
        "(sensitivity runs); the results are in `docs/results/risk_calendar.md`.",
        "",
        "## Risk calendar (`ASSUMPTIONS` in `src/compute/risk_calendar.py`)",
        "",
        table(ASSUMPTIONS),
        "",
        "## API (`API_ASSUMPTIONS` in `app.py`)",
        "",
        table(API_ASSUMPTIONS),
        "",
    ])


if __name__ == "__main__":
    with open(OUT_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write(build())
    print("wrote", OUT_MD)
